name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on:
      ubuntu-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test

      # Pack projects
      - name: .NET Pack
        run: dotnet pack --configuration Release --output ./artifacts -p:PackageVersion=0.0.${{github.run_number}}

      # Upload nuget package
      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
